version: "3.3"
services:
  app:
    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    ports:
      - ${DC_APP_PORT}:${DC_APP_PORT}`
    networks:
      - micro_service

networks:
  # option 1: Overwirte the name of the created docker network that docker-compose creates:
  #  micro_service:
  #    name: micro_service
  #    driver: bridge

  # option 2: Use an external network:
  micro_service:
    external:
      name: micro_service